version: "{build}"

init:
  - git config --global core.autocrlf input

install:
  - ps: .\appveyor.install.ps1

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "$(ASSEMBLY_VERSION)"
  assembly_file_version: "$(ASSEMBLY_FILE_VERSION)"
  assembly_informational_version: "$(ASSEMBLY_INFORMATIONAL_VERSION)"

platform: Any CPU

configuration: Release

build:
  publish_nuget: true

cache:
  - packages

deploy:
  - provider: NuGet
    api_key:
      secure: 9Wg2LEAupBmopvEh2VuikmrE32UwhsTWRsbXwhBnYspDELPopHrV3GjnCkj+WuWT
    artifact: /.*\.nupkg/
    on:
      deploy_nuget: true

notifications:
  - provider: Slack
    auth_token:
      secure: ZNvXZbUwux78d01rwXvMvCeXfPLFJ9soBT/ptmI8GYtNcAFuc9jASPUmW6LrxSOm
    channel: development
